DROP TABLE user_restaurant_votes IF EXISTS;
DROP TABLE restaurant_dishs IF EXISTS;
DROP TABLE restaurants IF EXISTS;
DROP TABLE user_roles IF EXISTS;
DROP TABLE users IF EXISTS;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS restaurant_dishs;
DROP TABLE IF EXISTS user_restaurant_votes;

DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;
CREATE TABLE users
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name             VARCHAR(255)                           NOT NULL,
    password         VARCHAR(255)                           NOT NULL,
    registered       TIMESTAMP           DEFAULT now() NOT NULL,
    enabled          BOOLEAN                DEFAULT TRUE  NOT NULL
);

CREATE TABLE user_roles
(
    user_id INTEGER NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE restaurants
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name             VARCHAR(255)                           NOT NULL
);

CREATE TABLE restaurant_dishs
(
    id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name          VARCHAR(255)                           NOT NULL,
    registered    TIMESTAMP           DEFAULT now() NOT NULL,
    price         INT                               NOT NULL,
    id_restaurant INTEGER                           NOT NULL,
    FOREIGN KEY (id_restaurant) REFERENCES restaurants (id) ON DELETE CASCADE
);

CREATE TABLE user_restaurant_votes
(
    id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    registered    TIMESTAMP           DEFAULT now() NOT NULL,
    id_user       INTEGER                           NOT NULL,
    id_restaurant INTEGER                           NOT NULL,
    FOREIGN KEY (id_user) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (id_restaurant) REFERENCES restaurants (id) ON DELETE CASCADE


);
